cmake_minimum_required(VERSION 3.20)
ADD_LIBRARY(png STATIC png.c)
TARGET_INCLUDE_DIRECTORIES(png PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
TARGET_INCLUDE_DIRECTORIES(png PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../miniz")
TARGET_INCLUDE_DIRECTORIES(png SYSTEM PUBLIC "${KERN_STDLIB_INCLUDE_DIR}")
TARGET_LINK_LIBRARIES(png PUBLIC miniz)
